const icons = {
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/><path d="M3 9h18"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-13 4h2m4 0h2m-8 3h2"/>',
 mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2m-7 9v3m-4 0h8"/>',
 spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7Z"/><path d="m20 2 .6 1.4L22 4l-1.4.6L20 6l-.6-1.4L18 4l1.4-.6Z"/>',
 chart:'<path d="M4 3v18h17M9 16v-5m5 5V6m5 10v-8"/>',
 building:'<path d="m3 8 9-5 9 5H3Zm2 3v7m5-7v7m4-7v7m5-7v7M3 21h18M2 18h20"/>',
 help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 0 1 6 0c0 2-3 2-3 4m0 3v.1"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',
 plus:'<path d="M12 5v14M5 12h14"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 file:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9Z"/><path d="M14 3v6h6M8 13h8m-8 4h5"/>',
 check:'<path d="m7 12 3 3 7-7"/><circle cx="12" cy="12" r="9"/>',
 scale:'<path d="M12 3v17M7 21h10M4 7l16-2M5 7l-4 8h8L5 7Zm14-2-4 8h8l-4-8ZM1 15c0 5 8 5 8 0m6-2c0 5 8 5 8 0"/>',
 download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>'
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.file}</svg>`;
const esc = text => String(text).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
document.querySelectorAll('[data-icon]').forEach(el => el.innerHTML = icon(el.dataset.icon));
const initialCases = [
 {id:'CIV-2026-0842',title:'Ahmed v. Malik',type:'Civil · Property dispute',status:'In progress',judge:'Justice S. Rahman',initials:'SR',date:'2026-09-12',time:'09:30',room:'Courtroom 03'},
 {id:'FAM-2026-0318',title:'Fatima v. Hassan',type:'Family · Guardianship',status:'Awaiting hearing',judge:'Justice A. Siddiqui',initials:'AS',date:'2026-09-12',time:'11:00',room:'Courtroom 01'},
 {id:'CIV-2026-0756',title:'Khan Enterprises v. Ali Trading',type:'Civil · Contract dispute',status:'In progress',judge:'Justice S. Rahman',initials:'SR',date:'2026-09-12',time:'14:00',room:'Courtroom 03'},
 {id:'CIV-2026-0621',title:'Raza v. Municipal Corporation',type:'Civil · Administrative',status:'Resolved',judge:'Justice M. Iqbal',initials:'MI',date:'2026-09-14',time:'10:00',room:'Courtroom 02'},
 {id:'CIV-2026-0903',title:'Noor v. Shah',type:'Civil · Property dispute',status:'Awaiting hearing',judge:'Justice A. Siddiqui',initials:'AS',date:'2026-09-15',time:'09:00',room:'Courtroom 01'}
];
// Retain the original storage key so existing case records survive the rebrand.
let saved = {};
try { saved = JSON.parse(localStorage.getItem('nizam-workspace') || '{}'); } catch {}
let cases = Array.isArray(saved.cases) && saved.cases.every(c => c.id && c.title && c.type && c.judge && c.initials && c.date && c.time && c.room && c.status) ? saved.cases : initialCases;
let notes = Array.isArray(saved.notes) ? saved.notes : [{id:'sample-note',caseId:'CIV-2026-0842',title:'Ahmed v. Malik — hearing notes',text:'SAMPLE HEARING NOTES\n\n09:30 — The matter was called in Courtroom 03.\n09:34 — The claimant presented the property documents for review.\n09:42 — The respondent requested time to submit a written response.\n\nFollow-up: Verify submitted documents and record the next hearing date after confirmation from the court.',date:'2026-09-12'}];
let selectedDay = '2026-09-12';
let messages = [];
let currentView = 'overview';
const navItems = [['overview','grid','Overview'],['cases','folder','Case management'],['hearings','calendar','Hearings'],['transcripts','mic','Transcripts'],['assistant','spark','AI assistant'],['analytics','chart','Analytics']];
const persist = () => { try { localStorage.setItem('nizam-workspace', JSON.stringify({cases,notes})); } catch { toast('Browser storage is unavailable. Changes last for this session only.'); } };
const main = document.getElementById('main');
const dialog = document.getElementById('dialog');
const badge = status => `<span class="badge ${status === 'Awaiting hearing' ? 'amber' : status === 'Resolved' ? 'purple' : ''}">${esc(status)}</span>`;
const formatDate = date => new Date(`${date}T12:00:00`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
function toast(message) { const el = document.getElementById('toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 3500); }
function heading(title,description,actions = '') { return `<div class="page-heading"><div><div class="eyebrow">YOUR JUDICIAL WORKSPACE</div><h1>${title}</h1><p>${description}</p></div><div class="heading-actions">${actions}</div></div>`; }
const newCaseButton = `<button class="btn primary" data-action="new-case">${icon('plus')} New case</button>`;
function stats() { const data = [['Active cases',cases.filter(c=>c.status!=='Resolved').length,'folder','Across your workspace','Currently open'],['Hearings today',cases.filter(c=>c.date==='2026-09-12'&&c.status!=='Resolved').length,'calendar','Saturday, 12 September','Scheduled'],['Hearing notes',notes.length,'file','Ready to review','Saved locally'],['Cases resolved',cases.filter(c=>c.status==='Resolved').length,'check','Of '+cases.length+' total cases','Completed']]; return `<div class="stats">${data.map(([title,value,symbol,description,label])=>`<div class="stat"><div class="stat-top"><span>${title}</span><span>${icon(symbol)}</span></div><div class="stat-number">${value}</div><div class="stat-bottom"><b>${label}</b> ${description}</div></div>`).join('')}</div>`; }
function calendar() { return `<div class="calendar-strip">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day,i)=>`<button class="day ${selectedDay === `2026-09-${String(i+7).padStart(2,'0')}`?'selected':''}" data-day="2026-09-${String(i+7).padStart(2,'0')}"><span>${day}</span><strong>${i+7}</strong><i></i></button>`).join('')}</div>`; }
function hearingsList() { const list = cases.filter(c=>c.date===selectedDay && c.status!=='Resolved').sort((a,b)=>a.time.localeCompare(b.time));return `<div class="hearings">${list.length?list.map((c,i)=>`<div class="hearing" role="button" tabindex="0" data-case="${esc(c.id)}"><div class="hearing-time">${String(Number(c.time.slice(0,2)) % 12 || 12).padStart(2,'0') + c.time.slice(2)}<small>${Number(c.time.slice(0,2))>=12?'PM':'AM'}</small></div><div class="hearing-bar ${i===1?'orange':i===2?'lavender':''}"></div><div class="hearing-info"><strong>${esc(c.title)}</strong><small>${esc(c.id)} <span>·</span> ${esc(c.room)}</small></div>${badge(c.status)}${icon('chevron')}</div>`).join(''):`<div class="empty">No hearings scheduled for ${formatDate(selectedDay)}.</div>`}</div>`; }
function hearingPanel(full = false) { return `<section class="panel ${full?'full-schedule':''}"><div class="panel-heading"><div><h2>${full?'Hearing schedule':"Your hearing schedule"}</h2><p>September 2026 <span>·</span> All courtrooms</p></div>${full?`<input type="date" aria-label="Select hearing date" id="schedule-date" value="${selectedDay}" class="btn">`:`<a class="text-link" href="#hearings">View calendar ${icon('arrow')}</a>`}</div>${calendar()}${hearingsList()}<div class="panel-footer">${icon('clock')} All times in Pakistan Standard Time (PKT)</div></section>`; }
function assistantCard(){return `<section class="assistant-card"><div class="assistant-heading"><span>✧</span><h2>Your court assistant</h2><small>PREVIEW</small></div><p>Less time looking. More time moving forward.<br>Find what matters in your workspace.</p><button class="suggestion" data-prompt="Summarize today’s hearings">Summarize today’s hearings ${icon('arrow')}</button><button class="suggestion" data-prompt="Which cases need attention?">Which cases need attention? ${icon('arrow')}</button><form class="assistant-input" id="quick-chat"><input aria-label="Ask CourtFlow" placeholder="Ask something about your cases…" required maxlength="1000"><button aria-label="Send message">${icon('arrow')}</button></form></section>`;}
function activityPanel(){return `<section class="panel"><div class="panel-heading"><h2>Workspace activity</h2><span class="text-link">Sample timeline</span></div><div class="activity-list"><div class="activity"><span class="activity-icon">${icon('file')}</span><div><p><b>Hearing notes ready for review</b><br>Ahmed v. Malik · CIV-2026-0842</p><small>12 September · 10:05 AM</small></div></div><div class="activity"><span class="activity-icon">${icon('calendar')}</span><div><p><b>Next hearing scheduled</b><br>Noor v. Shah · 15 September</p><small>12 September · 09:15 AM</small></div></div><div class="activity"><span class="activity-icon">${icon('check')}</span><div><p><b>Case marked as resolved</b><br>Raza v. Municipal Corporation</p><small>11 September · 04:30 PM</small></div></div></div></section>`;}
function caseTable(list) { return `<div class="table-scroll"><table><thead><tr><th>CASE NUMBER</th><th>CASE DETAILS</th><th>STATUS</th><th>PRESIDING JUDGE</th><th>HEARING DATE</th><th></th></tr></thead><tbody>${list.map(c=>`<tr tabindex="0" role="button" aria-label="Open ${esc(c.title)}" data-case="${esc(c.id)}"><td>${esc(c.id)}</td><td><strong>${esc(c.title)}</strong><small>${esc(c.type)}</small></td><td>${badge(c.status)}</td><td><span class="row-avatar">${esc(c.initials)}</span>${esc(c.judge.replace('Justice ',''))}</td><td>${formatDate(c.date)}</td><td>${icon('chevron')}</td></tr>`).join('')}</tbody></table>${list.length?'':'<div class="empty">No cases match your search.</div>'}</div>`; }
function render(){
 currentView = location.hash.slice(1) || 'overview'; if(!navItems.some(i=>i[0]===currentView)) currentView='overview';
 document.getElementById('navigation').innerHTML = navItems.map(([key,symbol,label])=>`<a href="#${key}" title="${label}" class="nav-item ${key===currentView?'active':''}" ${key===currentView?'aria-current="page"':''}><span>${icon(symbol)}</span><span>${label}</span>${key==='cases'?`<span class="count">${cases.length}</span>`:key==='assistant'?'<span class="new">NEW</span>':''}</a>`).join('');
 document.getElementById('page-label').textContent = navItems.find(i=>i[0]===currentView)[2];
 if(currentView==='overview') main.innerHTML = heading('A clearer day ahead, Ayesha.','Here’s what’s happening in your court today.',`<button class="btn date-button" data-action="calendar">${icon('calendar')} Sat, 12 Sep 2026</button>${newCaseButton}`)+`<section class="hero"><div class="hero-content"><div class="eyebrow">${icon('spark')} JUSTICE, WITH A LITTLE MORE CLARITY</div><h2>Less paperwork. More progress.</h2><p>Bring your cases, hearings, and records together.<br>Make room for the work that makes a difference.</p><button class="hero-link" data-prompt="Help me prepare for today">Let’s prepare for today ${icon('arrow')}</button></div><div class="hero-art" aria-hidden="true"><div class="ring"></div><div class="ring"></div><div class="ring"></div>${icon('scale')}<span class="spark">✧</span><span class="spark two">✧</span></div></section>`+stats()+`<div class="content-grid"><div>${hearingPanel()}</div><div class="right-column">${assistantCard()}${activityPanel()}</div></div><section class="panel recent-panel"><div class="panel-heading"><div><h2>Recent cases</h2><p>The details that keep things moving.</p></div><a class="text-link" href="#cases">View all cases ${icon('arrow')}</a></div>${caseTable(cases.slice(0,3))}</section>`;
 if(currentView==='cases') main.innerHTML=heading('Every case, in one place.','Search, organize, and keep the next step in sight.',newCaseButton)+`<section class="panel"><div class="panel-heading"><h2>Case register <span class="text-link">${cases.length} cases</span></h2><button class="btn" data-action="export">${icon('download')} Export CSV</button></div><div class="filters"><input id="case-search" aria-label="Search cases" placeholder="Search case number, party, or judge…"><select id="status-filter" aria-label="Filter by status"><option>All statuses</option><option>In progress</option><option>Awaiting hearing</option><option>Resolved</option></select></div><div id="case-results">${caseTable(cases)}</div></section>`;
 if(currentView==='hearings') main.innerHTML=heading('Make space for what’s next.','Plan hearings and keep your daily cause list in view.',newCaseButton)+hearingPanel(true);
 if(currentView==='transcripts') main.innerHTML=heading('A clear record of every hearing.','Create and review hearing notes. Audio transcription is not connected yet.',`<button class="btn primary" data-action="new-note">${icon('plus')} Add hearing notes</button>`)+notes.map(n=>`<section class="panel transcript-card"><span>${icon('file')}</span><div><h3>${esc(n.title)}</h3><p>${esc(n.caseId)} · ${formatDate(n.date)} · Hearing notes</p></div><button class="btn" data-note="${esc(n.id)}">Review notes ${icon('arrow')}</button></section>`).join('');
 if(currentView==='assistant') {main.innerHTML=heading('Your workspace, with a little help.','A local preview using your case register and saved notes.')+`<section class="chat-layout"><div class="chat-intro"><span>✧</span><h2>Let’s move the day forward.</h2><p>Ask about your hearing schedule, open cases, or hearing notes.<br>This demo uses local summaries. An AI model is not connected.</p><button class="btn" data-prompt="Summarize today’s hearings">${icon('calendar')} Today’s hearings</button> <button class="btn" data-prompt="Which cases need attention?">${icon('folder')} Cases needing attention</button></div><div id="messages">${messages.map(m=>`<div class="message ${m.role}"><small>${m.role==='user'?'YOU':'COURTFLOW · LOCAL PREVIEW'}</small>${esc(m.text)}</div>`).join('')}</div><form class="assistant-input" id="chat-form"><input aria-label="Message CourtFlow" placeholder="Ask about your workspace…" required maxlength="1000"><button aria-label="Send message">${icon('arrow')}</button></form></section>`;}
 if(currentView==='analytics') main.innerHTML=heading('A little perspective. Better progress.','A live view of the cases in this demo workspace.')+stats()+`<section class="panel"><div class="panel-heading"><h2>Case distribution</h2><span class="text-link">Current register</span></div><div class="analytics-chart"><div class="chart-bars">${['In progress','Awaiting hearing','Resolved'].map((s,i)=>{let n=cases.filter(c=>c.status===s).length;return `<div class="bar-group"><strong>${n}</strong><div class="bar" style="height:${n/Math.max(cases.length,1)*170}px;background:${['#333333','#aaaaaa','#737373'][i]}"></div><span>${s}</span></div>`;}).join('')}</div><p class="chart-note">Counts update as you create cases and change their status. This sample dataset does not represent court performance.</p></div></section>`;
}
function modal(title,body){document.getElementById('dialog-content').innerHTML=`<div class="modal-header"><h2>${title}</h2><button data-action="close" aria-label="Close dialog">×</button></div>${body}`;if(!dialog.open)dialog.showModal();}
function caseModal(id){const c=cases.find(c=>c.id===id);if(!c)return;modal(esc(c.title),`<p class="modal-copy">${esc(c.id)} · ${esc(c.type)}</p><div class="detail-grid"><div><small>PRESIDING JUDGE</small>${esc(c.judge)}</div><div><small>COURTROOM</small>${esc(c.room)}</div></div><form id="edit-case" data-id="${esc(c.id)}"><label class="field">Status<select name="status">${['In progress','Awaiting hearing','Resolved'].map(s=>`<option ${s===c.status?'selected':''}>${s}</option>`).join('')}</select></label><label class="field">Hearing date<input type="date" name="date" value="${esc(c.date)}" required></label><label class="field">Hearing time (PKT)<input type="time" name="time" value="${esc(c.time)}" required></label><div class="form-actions"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn primary">Save changes</button></div></form>`);}
function newCase(){modal('Create a new case',`<form id="new-case-form"><label class="field">Case title<input name="title" placeholder="e.g. Ahmed v. Malik" required maxlength="150"></label><label class="field">Case category<select name="type"><option>Civil · Property dispute</option><option>Civil · Contract dispute</option><option>Family · Guardianship</option><option>Civil · Administrative</option><option>Other</option></select></label><label class="field">Presiding judge<select name="judge"><option>Justice S. Rahman</option><option>Justice A. Siddiqui</option><option>Justice M. Iqbal</option></select></label><label class="field">Hearing date<input type="date" name="date" value="2026-09-12" required></label><label class="field">Hearing time (PKT)<input type="time" name="time" value="09:00" required></label><label class="field">Courtroom<select name="room"><option>Courtroom 01</option><option>Courtroom 02</option><option>Courtroom 03</option></select></label><div class="form-actions"><button type="button" class="btn" data-action="close">Cancel</button><button class="btn primary">Create case</button></div></form>`);}
function noteModal(id){const n=notes.find(n=>n.id===id);modal(n?'Review hearing notes':'Add hearing notes',`<form id="note-form" data-id="${n?esc(n.id):''}"><label class="field">Related case<select name="caseId">${cases.map(c=>`<option value="${esc(c.id)}" ${n?.caseId===c.id?'selected':''}>${esc(c.id)} · ${esc(c.title)}</option>`).join('')}</select></label><label class="field">Title<input name="title" value="${n?esc(n.title):''}" placeholder="Hearing notes" required maxlength="150"></label><label class="field">Notes<textarea name="text" rows="9" required maxlength="30000" placeholder="Record the hearing and follow-up actions…">${n?esc(n.text):''}</textarea></label><p class="modal-copy">Saved in this browser. This prototype has no cloud backup or audio transcription.</p><div class="form-actions">${n?`<button type="button" class="btn" data-download-note="${esc(n.id)}">${icon('download')} Download</button>`:''}<button class="btn primary">Save notes</button></div></form>`);}
function ask(prompt){messages.push({role:'user',text:prompt});let response;const query=prompt.toLowerCase();const match=cases.find(c=>query.includes(c.id.toLowerCase())||query.includes(c.title.toLowerCase()));if(match){const attached=notes.filter(n=>n.caseId===match.id);response=`${match.title} (${match.id})\nStatus: ${match.status}\nHearing: ${formatDate(match.date)} at ${match.time} PKT\n${match.room} · ${match.judge}\n\n${attached.length?attached.map(n=>n.text).join('\n\n'):'No hearing notes have been saved for this case.'}`;}else if(/today|hearing|prepare|schedule/.test(query)){const list=cases.filter(c=>c.date==='2026-09-12'&&c.status!=='Resolved').sort((a,b)=>a.time.localeCompare(b.time));response=`For the demo date, 12 September 2026, you have ${list.length} hearings:\n\n${list.map(c=>`${c.time} PKT — ${c.title}\n${c.room} · ${c.id}`).join('\n\n')}\n\nBefore each hearing, review the case record and confirm any outstanding documents with the court team.`;}else if(/attention|open|pending|case/.test(query)){const list=cases.filter(c=>c.status==='Awaiting hearing');response=`${list.length} cases are awaiting a hearing:\n\n${list.map(c=>`${c.title} · ${c.id}\n${formatDate(c.date)} at ${c.time} PKT — ${c.room}`).join('\n\n')}\n\nOpen a case to review its schedule or update its status. These are status-based results, not an assessment of legal urgency.`;}else if(/note|transcript/.test(query)){response=`There are ${notes.length} saved hearing notes:\n\n${notes.map(n=>`${n.title} · ${n.caseId}`).join('\n')}\n\nYou can review, edit, and download them from Transcripts.`;}else{response='This local preview can summarize today’s hearings, list cases awaiting a hearing, and find saved hearing notes. Try a case title or case number, or ask “Which cases need attention?”\n\nConnect an AI provider to enable broader document analysis and open-ended questions.';}messages.push({role:'assistant',text:response});if(location.hash!=='#assistant')location.hash='assistant';else render();}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action],[data-case],[data-day],[data-prompt],[data-note],[data-download-note]');if(!b)return;if(b.dataset.case)return caseModal(b.dataset.case);if(b.dataset.day){selectedDay=b.dataset.day;return render();}if(b.dataset.prompt)return ask(b.dataset.prompt);if(b.dataset.note)return noteModal(b.dataset.note);if(b.dataset.downloadNote){const n=notes.find(n=>n.id===b.dataset.downloadNote);if(n)download(`${n.caseId}-notes.txt`,n.text,'text/plain');return;}switch(b.dataset.action){case'new-case':newCase();break;case'close':dialog.close();break;case'calendar':location.hash='hearings';break;case'new-note':noteModal();break;case'export':{const rows=[['Case number','Title','Type','Status','Judge','Date','Time','Courtroom'],...cases.map(c=>[c.id,c.title,c.type,c.status,c.judge,c.date,c.time,c.room])];download('courtflow-cases.csv',rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n'),'text/csv');toast('Case register exported.');break;}}});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-case]')){e.preventDefault();caseModal(e.target.dataset.case);}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target;const data=Object.fromEntries(new FormData(form));if(form.id==='new-case-form'){if(!data.title.trim())return;const initials={'Justice S. Rahman':'SR','Justice A. Siddiqui':'AS','Justice M. Iqbal':'MI'};cases.unshift({...data,title:data.title.trim(),id:`${data.type.startsWith('Family')?'FAM':'CIV'}-2026-${String(Math.max(1000,...cases.map(c=>Number(c.id.split('-').at(-1))||0))+1).padStart(4,'0')}`,status:'Awaiting hearing',initials:initials[data.judge]});persist();dialog.close();render();toast('Case created and hearing scheduled.');}if(form.id==='edit-case'){Object.assign(cases.find(c=>c.id===form.dataset.id),data);persist();dialog.close();render();toast('Case updated.');}if(form.id==='note-form'){if(!data.title.trim()||!data.text.trim())return;const existing=notes.find(n=>n.id===form.dataset.id);if(existing)Object.assign(existing,data);else notes.unshift({...data,id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10)});persist();dialog.close();render();toast('Hearing notes saved.');}if(form.id==='quick-chat'||form.id==='chat-form'){const input=form.querySelector('input');if(input.value.trim())ask(input.value.trim());}});
function filterCases(){const query=document.getElementById('case-search').value.toLowerCase();const status=document.getElementById('status-filter').value;document.getElementById('case-results').innerHTML=caseTable(cases.filter(c=>(status==='All statuses'||c.status===status)&&[c.title,c.id,c.judge,c.type].some(v=>v.toLowerCase().includes(query))));}
document.addEventListener('input',e=>{if(e.target.id==='case-search')filterCases();});
document.addEventListener('change',e=>{if(e.target.id==='status-filter')filterCases();if(e.target.id==='schedule-date'&&e.target.value){selectedDay=e.target.value;render();}});
document.getElementById('help-button').onclick=()=>modal('Welcome to CourtFlow',`<p class="modal-copy">Your first workspace for clearer court operations.</p><p class="modal-copy"><b>Case management</b> — Create a case, search the register, update its status, and schedule its hearing.<br><br><b>Hearings</b> — Select a date to see that day’s cause list.<br><br><b>Transcripts</b> — Write, review, and download hearing notes.<br><br><b>AI assistant</b> — Explore a local summary preview using your saved case data.</p><p class="modal-copy">This is a prototype with fictional cases and a fixed overview date of 12 September 2026. Records are stored only in this browser. Authentication, server storage, and AI transcription are not connected.</p><div class="form-actions"><button class="btn primary" data-action="close">Let’s get started</button></div>`);
document.getElementById('notifications').onclick=()=>modal('You’re all caught up',`<p class="modal-copy">There are no new notifications in this demo workspace. You can review the sample timeline on your overview.</p><div class="form-actions"><button class="btn primary" data-action="close">Got it</button></div>`);
dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
render();
